# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='GeoCoordinate.proto',
  package='bfd',
  serialized_pb='\n\x13GeoCoordinate.proto\x12\x03\x62\x66\x64\"X\n\rGeoCoordinate\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01\x12\x10\n\x08\x64istrict\x18\x03 \x01(\t\x12\x10\n\x08\x64istance\x18\x04 \x01(\x01')




_GEOCOORDINATE = descriptor.Descriptor(
  name='GeoCoordinate',
  full_name='bfd.GeoCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='latitude', full_name='bfd.GeoCoordinate.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='longitude', full_name='bfd.GeoCoordinate.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='district', full_name='bfd.GeoCoordinate.district', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='distance', full_name='bfd.GeoCoordinate.distance', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['GeoCoordinate'] = _GEOCOORDINATE

class GeoCoordinate(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GEOCOORDINATE
  
  # @@protoc_insertion_point(class_scope:bfd.GeoCoordinate)

# @@protoc_insertion_point(module_scope)
