class Industry(object):
    INDUSTRY_NONE = 0
    INDUSTRY_TUAN = 1
    INDUSTRY_JIA_DIAN = 2
    INDUSTRY_HUA_ZHUANG_PIN = 3
    INDUSTRY_TRAVEL = 4
    INDUSTRY_WINE = 5
    INDUSTRY_CLOTHES = 6
    INDUSTRY_MEDICINE = 7
    INDUSTRY_ESTATE = 8
    INDUSTRY_SOFTWARE = 9